begin;
select plan(16);
select ok(to_regclass('public.whatsapp_links') is not null,'whatsapp_links existe');
select ok(to_regclass('public.whatsapp_pairing_codes') is not null,'whatsapp_pairing_codes existe');
select ok(to_regclass('public.whatsapp_messages') is not null,'whatsapp_messages existe');
select ok(to_regclass('public.financial_drafts') is not null,'financial_drafts existe');
select ok(to_regclass('public.draft_corrections') is not null,'draft_corrections existe');
select is((select relrowsecurity from pg_class where oid='public.whatsapp_links'::regclass),true,'whatsapp_links usa RLS');
select is((select relrowsecurity from pg_class where oid='public.financial_drafts'::regclass),true,'financial_drafts usa RLS');
select function_privs_are('public','confirm_whatsapp_draft',array['uuid']::name[], 'service_role', array['EXECUTE']);
select function_privs_are('public','claim_whatsapp_message',array['uuid','text','text','jsonb']::name[], 'service_role', array['EXECUTE']);
select function_privs_are('public','create_whatsapp_draft',array['uuid','uuid','jsonb']::name[], 'service_role', array['EXECUTE']);
select function_privs_are('public','process_whatsapp_command',array['uuid','uuid','text','jsonb']::name[], 'service_role', array['EXECUTE']);
select function_privs_are('public','consume_whatsapp_pairing_code',array['uuid','text','text','text']::name[], 'service_role', array['EXECUTE']);
select function_privs_are('public','create_whatsapp_pairing_code',array[]::name[], 'authenticated', array['EXECUTE']);
select function_privs_are('public','prepare_receipt_import',array['uuid','text']::name[], 'authenticated', array['EXECUTE']);
select function_privs_are('public','dispatch_whatsapp_text',array['uuid','uuid','text','jsonb','jsonb']::name[], 'service_role', array['EXECUTE']);
select function_privs_are('public','claim_abandoned_receipt_imports',array['integer']::name[], 'service_role', array['EXECUTE']);
select * from finish();
rollback;
