begin;
select plan(16);
select has_table('public','whatsapp_links');
select has_table('public','whatsapp_pairing_codes');
select has_table('public','whatsapp_messages');
select has_table('public','financial_drafts');
select has_table('public','draft_corrections');
select row_security_active('public','whatsapp_links');
select row_security_active('public','financial_drafts');
select function_privs_are('public','confirm_whatsapp_draft',array['uuid']::name[], 'service_role', array['EXECUTE']);
select function_privs_are('public','claim_whatsapp_message',array['uuid','text','text','jsonb']::name[], 'service_role', array['EXECUTE']);
select function_privs_are('public','create_whatsapp_draft',array['uuid','uuid','jsonb']::name[], 'service_role', array['EXECUTE']);
select function_privs_are('public','process_whatsapp_command',array['uuid','uuid','text','jsonb']::name[], 'service_role', array['EXECUTE']);
select function_privs_are('public','consume_whatsapp_pairing_code',array['uuid','text','text','text']::name[], 'service_role', array['EXECUTE']);
select function_privs_are('public','create_whatsapp_pairing_code',array[]::name[], 'authenticated', array['EXECUTE']);
select function_privs_are('public','prepare_receipt_import',array['uuid','text']::name[], 'authenticated', array['EXECUTE']);
select function_privs_are('public','dispatch_whatsapp_text',array['uuid','uuid','text','jsonb','jsonb']::name[], 'service_role', array['EXECUTE']);
select function_privs_are('public','claim_abandoned_receipt_imports',array['integer']::name[], 'service_role', array['EXECUTE']);
select * from finish();
rollback;
