import React from "react";
import { Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { CATEGORY_COLORS, C } from "../theme.js";
import { money } from "../utils.js";
import { Panel } from "../components/Common.jsx";

const tooltipStyle={background:C.surface2,border:`1px solid ${C.divider}`,borderRadius:14,color:C.text,fontSize:12};

export default function AnalyticsPage({ metrics, monthlySeries }) {
  const cutCandidates=metrics.categoryData.filter((item)=>item.percentage>=8).slice(0,4);
  return <div className="page-stack">
    <div className="page-intro"><div><span className="eyebrow">Dados que viram decisão</span><h1>Análises</h1><p>Tendências, formas de pagamento e oportunidades calculadas a partir dos seus lançamentos.</p></div></div>
    <div className="analytics-summary"><div><span>Receita</span><strong>{money(metrics.income)}</strong></div><div><span>Gastos</span><strong>{money(metrics.expense)}</strong></div><div><span>Investido</span><strong>{money(metrics.investments)}</strong></div><div><span>Sobra estimada</span><strong>{money(metrics.projectedBalance)}</strong></div></div>
    <div className="dashboard-grid dashboard-grid-main"><Panel title="Tendência mensal" subtitle="Receita, gastos e investimentos" className="span-2"><div className="chart-large"><ResponsiveContainer><BarChart data={monthlySeries}><CartesianGrid stroke={C.divider} vertical={false}/><XAxis dataKey="label" tick={{fill:C.textSoft,fontSize:11}} axisLine={false}/><YAxis tick={{fill:C.textSoft,fontSize:10}} axisLine={false}/><Tooltip contentStyle={tooltipStyle} formatter={(v,n)=>[money(v),n]}/><Legend/><Bar dataKey="receitas" fill={C.lavender} radius={[5,5,0,0]}/><Bar dataKey="despesas" fill={C.purple} radius={[5,5,0,0]}/><Bar dataKey="investimentos" fill={C.pink} radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></Panel>
    <Panel title="Categorias" subtitle="Participação no total de gastos"><div className="chart-donut"><ResponsiveContainer><PieChart><Pie data={metrics.categoryData} dataKey="value" nameKey="name" innerRadius={48} outerRadius={76}>{metrics.categoryData.map((item,i)=><Cell key={item.name} fill={CATEGORY_COLORS[i%CATEGORY_COLORS.length]}/>)}</Pie><Tooltip contentStyle={tooltipStyle} formatter={(v,n)=>[money(v),n]}/></PieChart></ResponsiveContainer></div><div className="legend-list">{metrics.categoryData.slice(0,7).map((item,i)=><div key={item.name}><span className="legend-dot" style={{background:CATEGORY_COLORS[i%CATEGORY_COLORS.length]}}/><span>{item.name}</span><strong>{item.percentage.toFixed(1)}%</strong></div>)}</div></Panel></div>
    <div className="dashboard-grid dashboard-grid-secondary"><Panel title="Pix x cartão" subtitle="Evolução por mês" className="span-2"><div className="chart-medium"><ResponsiveContainer><BarChart data={monthlySeries}><CartesianGrid stroke={C.divider} vertical={false}/><XAxis dataKey="label" tick={{fill:C.textSoft,fontSize:11}} axisLine={false}/><YAxis tick={{fill:C.textSoft,fontSize:10}} axisLine={false}/><Tooltip contentStyle={tooltipStyle} formatter={(v,n)=>[money(v),n==="pix"?"Pix":"Cartão"]}/><Legend formatter={(v)=>v==="pix"?"Pix":"Cartão"}/><Bar dataKey="pix" fill={C.lavender} radius={[5,5,0,0]}/><Bar dataKey="cartao" fill={C.purple} radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></Panel><Panel title="Leitura do período" subtitle="Sem julgamentos, apenas sinais"><div className="insight-list">{metrics.insights.map((item,i)=><div key={i}><span>{String(i+1).padStart(2,"0")}</span><p>{item}</p></div>)}</div></Panel></div>
    <Panel title="Onde posso economizar?" subtitle="Simulações simples com base nas maiores categorias"><div className="cut-grid">{cutCandidates.length?cutCandidates.map((item)=><article key={item.name}><span>{item.name}</span><strong>{money(item.value)}</strong><p>Reduzindo 20%, você liberaria aproximadamente <b>{money(item.value*.2)}</b> neste período.</p><small>Estimativa, não recomendação obrigatória.</small></article>):<p className="empty-text">Adicione despesas para gerar oportunidades de redução.</p>}</div></Panel>
  </div>;
}
